This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./TFG.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file TFG.acn....done (127 entries accepted, 0 rejected).
Sorting entries....done (988 comparisons).
Generating output file TFG.acr....done (80 lines written, 0 warnings).
Output written in TFG.acr.
Transcript written in TFG.alg.
