
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versi├│n de MSBuild 17.13.19+0d9f5a35a para .NET Framework
      Compilaci├│n iniciada a las 14/05/2025 18:06:05.
      
      Proyecto "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.vcxproj" en nodo 1 (destinos predeterminados).
      PrepareForBuild:
        Creando directorio "Debug\\".
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Creando directorio "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Se crear├í "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" porque se especific├│ "AlwaysCreate".
        Aplicando tarea Touch a "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      VcpkgTripletSelection:
        Using triplet "x64-windows" from "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\"
        Using normalized configuration "Release"
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\CL.exe /c /I"C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\include" /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\lib" /LIBPATH:"C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.exe
      AppLocalFromInstalled:
        pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\bogurad\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.exe" "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"
        "pwsh.exe" no se reconoce como un comando interno o externo,
        programa o archivo por lotes ejecutable.
        El comando "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\bogurad\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.exe" "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"" sali├│ con el c├│digo 9009.
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\bogurad\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.exe" "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Se eliminar├í el archivo "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Aplicando tarea Touch a "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Compilaci├│n del proyecto terminada "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.vcxproj" (destinos predeterminados).
      
      Compilaci├│n correcta.
          0 Advertencia(s)
          0 Errores
      
      Tiempo transcurrido 00:00:01.07
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/bogurad/Desktop/Proyectos gitHub/TFG2/Codigo/Algoritmos postcuanticos/KAT_tests/kyber512/kat_test/build_kat_512/CMakeFiles/4.0.2/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/bogurad/Desktop/Proyectos gitHub/TFG2/Codigo/Algoritmos postcuanticos/KAT_tests/kyber512/kat_test/build_kat_512/CMakeFiles/CMakeScratch/TryCompile-14awxd"
      binary: "C:/Users/bogurad/Desktop/Proyectos gitHub/TFG2/Codigo/Algoritmos postcuanticos/KAT_tests/kyber512/kat_test/build_kat_512/CMakeFiles/CMakeScratch/TryCompile-14awxd"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/bogurad/Desktop/Proyectos gitHub/TFG2/Codigo/Algoritmos postcuanticos/KAT_tests/kyber512/kat_test/build_kat_512/CMakeFiles/CMakeScratch/TryCompile-14awxd'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_523ac.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versi├│n de MSBuild 17.13.19+0d9f5a35a para .NET Framework
        Compilaci├│n iniciada a las 14/05/2025 18:06:07.
        
        Proyecto "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\CMakeScratch\\TryCompile-14awxd\\cmTC_523ac.vcxproj" en nodo 1 (destinos predeterminados).
        PrepareForBuild:
          Creando directorio "cmTC_523ac.dir\\Debug\\".
          Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
          Creando directorio "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\CMakeScratch\\TryCompile-14awxd\\Debug\\".
          Creando directorio "cmTC_523ac.dir\\Debug\\cmTC_523ac.tlog\\".
        InitializeBuildStatus:
          Se crear├í "cmTC_523ac.dir\\Debug\\cmTC_523ac.tlog\\unsuccessfulbuild" porque se especific├│ "AlwaysCreate".
          Aplicando tarea Touch a "cmTC_523ac.dir\\Debug\\cmTC_523ac.tlog\\unsuccessfulbuild".
        VcpkgTripletSelection:
          Using triplet "x64-windows" from "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\"
          Using normalized configuration "Debug"
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\CL.exe /c /I"C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\include" /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_523ac.dir\\Debug\\\\" /Fd"cmTC_523ac.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.43.34810 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /I"C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\include" /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_523ac.dir\\Debug\\\\" /Fd"cmTC_523ac.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\CMakeScratch\\TryCompile-14awxd\\Debug\\cmTC_523ac.exe" /INCREMENTAL /ILK:"cmTC_523ac.dir\\Debug\\cmTC_523ac.ilk" /NOLOGO /LIBPATH:"C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\debug\\lib" /LIBPATH:"C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\debug\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\debug\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/bogurad/Desktop/Proyectos gitHub/TFG2/Codigo/Algoritmos postcuanticos/KAT_tests/kyber512/kat_test/build_kat_512/CMakeFiles/CMakeScratch/TryCompile-14awxd/Debug/cmTC_523ac.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/bogurad/Desktop/Proyectos gitHub/TFG2/Codigo/Algoritmos postcuanticos/KAT_tests/kyber512/kat_test/build_kat_512/CMakeFiles/CMakeScratch/TryCompile-14awxd/Debug/cmTC_523ac.lib" /MACHINE:X64  /machine:x64 cmTC_523ac.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_523ac.vcxproj -> C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\CMakeScratch\\TryCompile-14awxd\\Debug\\cmTC_523ac.exe
        AppLocalFromInstalled:
          pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\bogurad\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\CMakeScratch\\TryCompile-14awxd\\Debug\\cmTC_523ac.exe" "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\debug\\bin" "cmTC_523ac.dir\\Debug\\cmTC_523ac.tlog\\cmTC_523ac.write.1u.tlog" "cmTC_523ac.dir\\Debug\\vcpkg.applocal.log"
          "pwsh.exe" no se reconoce como un comando interno o externo,
          programa o archivo por lotes ejecutable.
          El comando "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\bogurad\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\CMakeScratch\\TryCompile-14awxd\\Debug\\cmTC_523ac.exe" "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\debug\\bin" "cmTC_523ac.dir\\Debug\\cmTC_523ac.tlog\\cmTC_523ac.write.1u.tlog" "cmTC_523ac.dir\\Debug\\vcpkg.applocal.log"" sali├│ con el c├│digo 9009.
          "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\bogurad\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\CMakeScratch\\TryCompile-14awxd\\Debug\\cmTC_523ac.exe" "C:\\Users\\bogurad\\vcpkg\\installed\\x64-windows\\debug\\bin" "cmTC_523ac.dir\\Debug\\cmTC_523ac.tlog\\cmTC_523ac.write.1u.tlog" "cmTC_523ac.dir\\Debug\\vcpkg.applocal.log"
        FinalizeBuildStatus:
          Se eliminar├í el archivo "cmTC_523ac.dir\\Debug\\cmTC_523ac.tlog\\unsuccessfulbuild".
          Aplicando tarea Touch a "cmTC_523ac.dir\\Debug\\cmTC_523ac.tlog\\cmTC_523ac.lastbuildstate".
        Compilaci├│n del proyecto terminada "C:\\Users\\bogurad\\Desktop\\Proyectos gitHub\\TFG2\\Codigo\\Algoritmos postcuanticos\\KAT_tests\\kyber512\\kat_test\\build_kat_512\\CMakeFiles\\CMakeScratch\\TryCompile-14awxd\\cmTC_523ac.vcxproj" (destinos predeterminados).
        
        Compilaci├│n correcta.
            0 Advertencia(s)
            0 Errores
        
        Tiempo transcurrido 00:00:01.07
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.43.34808/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:270 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Running the C compiler's linker: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.43.34808/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.43.34810.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
